# 워크플로우 -> 자동화 할 작업의 설계서 -> action.yml
#

name: first workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # actions 재사용 가능한 작업

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: install dependencies
        run: npm ci

      - name: build
        run: npm run build

  #run lint
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
